url_list = {
    "test": ["https://en.wikipedia.org/wiki/Typhoon_Kyle_(1993)", "https://en.wikipedia.org/wiki/Typhoon_Morakot", "https://en.wikipedia.org/wiki/Cyclone_Quimburga",
          "https://en.wikipedia.org/wiki/Hurricane_Irma", "https://en.wikipedia.org/wiki/Hurricane_Ginny", "https://en.wikipedia.org/wiki/Cyclone_Niran",
          "https://en.wikipedia.org/wiki/2022_South_Korean_floods", "https://en.wikipedia.org/wiki/Typhoon_Gene", "https://en.wikipedia.org/wiki/Sandalwood_Fire",
          "https://en.wikipedia.org/wiki/Hurricane_Fiona", "https://en.wikipedia.org/wiki/Hurricane_Ike", "https://en.wikipedia.org/wiki/Cyclone_Trina",
          "https://en.wikipedia.org/wiki/1933_Trinidad_hurricane", "https://en.wikipedia.org/wiki/Cyclone_Ockhi", "https://en.wikipedia.org/wiki/Hurricane_Bob_(1979)",
          "https://en.wikipedia.org/wiki/Cyclone_Idai", "https://en.wikipedia.org/wiki/February_flood_of_1825", "https://en.wikipedia.org/wiki/Cyclone_Gombe",
          "https://en.wikipedia.org/wiki/Hurricane_Alice_(December_1954)", "https://en.wikipedia.org/wiki/1899_San_Ciriaco_hurricane", "https://en.wikipedia.org/wiki/Hurricane_Cleo",
          "https://en.wikipedia.org/wiki/Black_Sunday_(storm)", "https://en.wikipedia.org/wiki/Tropical_Storm_Norman_(2006)", "https://en.wikipedia.org/wiki/Hurricane_Michael",
          "https://en.wikipedia.org/wiki/2006%E2%80%932007_Southeast_Asian_floods", "https://en.wikipedia.org/wiki/Cyclone_Raja", "https://en.wikipedia.org/wiki/Hurricane_Frank_(2010)",
          "https://en.wikipedia.org/wiki/Typhoon_Nalgae_(2011)", "https://en.wikipedia.org/wiki/Typhoon_Billie_(1959)", "https://en.wikipedia.org/wiki/Hurricane_Edouard_(1996)",
          "https://en.wikipedia.org/wiki/Late_December_2012_North_American_storm_complex", "https://en.wikipedia.org/wiki/Tropical_Storm_Fernand_(2019)",
          "https://en.wikipedia.org/wiki/Tropical_Storm_Doria", "https://en.wikipedia.org/wiki/Typhoon_Man-yi_(2013)", "https://en.wikipedia.org/wiki/Great_Flood_of_1771",
          "https://en.wikipedia.org/wiki/Tropical_Depression_One_(1988)", "https://en.wikipedia.org/wiki/Hurricane_Matthew", "https://en.wikipedia.org/wiki/January_2013_Northwest_Pacific_cyclone",
          "https://en.wikipedia.org/wiki/Storm_Carmel", "https://en.wikipedia.org/wiki/Hurricane_Rick_(2021)", "https://en.wikipedia.org/wiki/Hurricane_Kenneth_(2005)",
          "https://en.wikipedia.org/wiki/Tropical_Storm_Charley_(1998)", "https://en.wikipedia.org/wiki/Hurricane_Gert", "https://en.wikipedia.org/wiki/Hurricane_Martha",
          "https://en.wikipedia.org/wiki/Hurricane_Felicia_(2009)", "https://en.wikipedia.org/wiki/February_25%E2%80%9327,_2010_North_American_blizzard", "https://en.wikipedia.org/wiki/Typhoon_Melor",
          "https://en.wikipedia.org/wiki/2016_Ethiopian_flood", "https://en.wikipedia.org/wiki/Hurricane_Lili", "https://en.wikipedia.org/wiki/Hurricane_Karen_(2001)",
          "https://en.wikipedia.org/wiki/Storm_Alex", "https://en.wikipedia.org/wiki/Tropical_Storm_Warren_(1984)", "https://en.wikipedia.org/wiki/Tropical_Storm_Winona_(1990)",
          "https://en.wikipedia.org/wiki/1925_Florida_tropical_storm", "https://en.wikipedia.org/wiki/Typhoon_Nina_(1987)", "https://en.wikipedia.org/wiki/Cyclone_Laurence",
          "https://en.wikipedia.org/wiki/Tropical_Storm_Vicente_(2018)", "https://en.wikipedia.org/wiki/Cyclone_Giri", "https://en.wikipedia.org/wiki/Tropical_Storm_Laura_(2008)",
          "https://en.wikipedia.org/wiki/Cyclone_Debbie", "https://en.wikipedia.org/wiki/Typhoon_Fanapi", "https://en.wikipedia.org/wiki/1932_Freeport_hurricane",
          "https://en.wikipedia.org/wiki/Typhoon_Nabi", "https://en.wikipedia.org/wiki/Hurricane_Klaus_(1990)", "https://en.wikipedia.org/wiki/2015_Accra_floods",
          "https://en.wikipedia.org/wiki/Hurricane_Gustav", "https://en.wikipedia.org/wiki/Tropical_Storm_Danielle_(1992)", "https://en.wikipedia.org/wiki/Boundary_Waters%E2%80%93Canadian_derecho",
          "https://en.wikipedia.org/wiki/Cyclone_John", "https://en.wikipedia.org/wiki/1966_Venice_flood", "https://en.wikipedia.org/wiki/Typhoon_Nari_(2013)",
          "https://en.wikipedia.org/wiki/Cyclone_Orson", "https://en.wikipedia.org/wiki/Typhoon_Judy_(1982)", "https://en.wikipedia.org/wiki/Tropical_Storm_Linda_(1997)",
          "https://en.wikipedia.org/wiki/Hurricane_Pali", "https://en.wikipedia.org/wiki/Typhoon_Nock-ten", "https://en.wikipedia.org/wiki/Hurricane_Maria_(2011)",
          "https://en.wikipedia.org/wiki/Typhoon_Nora_(1973)", "https://en.wikipedia.org/wiki/Typhoon_Jebi", "https://en.wikipedia.org/wiki/Hurricane_Beatriz_(2011)",
          "https://en.wikipedia.org/wiki/Tropical_Storm_Sinlaku_(2020)", "https://en.wikipedia.org/wiki/Cyclone_Alby", "https://en.wikipedia.org/wiki/Cyclone_Anne_(2014)",
          "https://en.wikipedia.org/wiki/Hurricane_Gert_(1999)", "https://en.wikipedia.org/wiki/2013_North_India_floods", "https://en.wikipedia.org/wiki/2015_Northern_Chile_floods_and_mudflow",
          "https://en.wikipedia.org/wiki/Storm_Eunice", "https://en.wikipedia.org/wiki/Hurricane_Betsy_(1956)", "https://en.wikipedia.org/wiki/February_9%E2%80%9311,_2017_North_American_blizzard",
          "https://en.wikipedia.org/wiki/2013_Argentina_floods", "https://en.wikipedia.org/wiki/Late_March_2016_North_American_blizzard", "https://en.wikipedia.org/wiki/Hurricane_Tico",
          "https://en.wikipedia.org/wiki/1964_Rameswaram_cyclone", "https://en.wikipedia.org/wiki/Hurricane_Charley_(1986)", "https://en.wikipedia.org/wiki/2017_California_floods",
          "https://en.wikipedia.org/wiki/Cyclone_Monty", "https://en.wikipedia.org/wiki/January_2016_United_States_blizzard", "https://en.wikipedia.org/wiki/2021_Eurasia_winter_heatwave",
          "https://en.wikipedia.org/wiki/Typhoon_Nida_(2004)", "https://en.wikipedia.org/wiki/2022_Southern_Cone_heat_wave", "https://en.wikipedia.org/wiki/January_2012_Pacific_Northwest_snowstorm",
          "https://en.wikipedia.org/wiki/Hurricane_Dot_(1959)", "https://en.wikipedia.org/wiki/1922_Shantou_typhoon", "https://en.wikipedia.org/wiki/Tropical_Storm_Nestor_(2019)",
          "https://en.wikipedia.org/wiki/Hurricane_Orlene_(2022)", "https://en.wikipedia.org/wiki/Hurricane_Rafael", "https://en.wikipedia.org/wiki/Typhoon_Irma_(1981)",
          "https://en.wikipedia.org/wiki/Hurricane_Henri", "https://en.wikipedia.org/wiki/1876_San_Felipe_hurricane", "https://en.wikipedia.org/wiki/Hurricane_Tanya",
          "https://en.wikipedia.org/wiki/Independence_Day_Derecho_of_1977", "https://en.wikipedia.org/wiki/Early_2014_Sabah_floods", "https://en.wikipedia.org/wiki/Tropical_Storm_Etau_(2009)",
          "https://en.wikipedia.org/wiki/1945_Outer_Banks_hurricane", "https://en.wikipedia.org/wiki/Tropical_Storm_Kiko_(2007)", "https://en.wikipedia.org/wiki/Typhoon_Talim_(2017)",
          "https://en.wikipedia.org/wiki/Typhoon_Neoguri_(2014)", "https://en.wikipedia.org/wiki/Typhoon_Skip", "https://en.wikipedia.org/wiki/Tropical_Storm_Abby_(1964)",
          "https://en.wikipedia.org/wiki/Tropical_Storm_Hermine_(2010)", "https://en.wikipedia.org/wiki/Hurricane_Leslie_(2018)", "https://en.wikipedia.org/wiki/Typhoon_Kate_(1970)",
          "https://en.wikipedia.org/wiki/Cyclone_Berguitta", "https://en.wikipedia.org/wiki/Hurricane_Hilary_(1993)", "https://en.wikipedia.org/wiki/2011_China_floods",
          "https://en.wikipedia.org/wiki/Cyclone_Ita", "https://en.wikipedia.org/wiki/Tropical_Storm_Kelly", "https://en.wikipedia.org/wiki/1888_Moradabad_hailstorm",
          "https://en.wikipedia.org/wiki/2016_Maryland_flood", "https://en.wikipedia.org/wiki/Typhoon_Cary_(1987)", "https://en.wikipedia.org/wiki/1998_Gujarat_cyclone",
          "https://en.wikipedia.org/wiki/St._Lucia%27s_flood", "https://en.wikipedia.org/wiki/Cyclone_Quimburga", "https://en.wikipedia.org/wiki/1933_Treasure_Coast_hurricane",
          "https://en.wikipedia.org/wiki/Cyclone_Apollo", "https://en.wikipedia.org/wiki/Hurricane_Fiona", "https://en.wikipedia.org/wiki/Columbus_Day_Storm_of_1962",
          "https://en.wikipedia.org/wiki/Hurricane_Humberto_(2019)", "https://en.wikipedia.org/wiki/Tropical_Storm_Kirk_(2018)", "https://en.wikipedia.org/wiki/Tropical_Storm_Josephine_(1996)",
          "https://en.wikipedia.org/wiki/Cyclone_Carmen", "https://en.wikipedia.org/wiki/Typhoon_Mamie_(1985)", "https://en.wikipedia.org/wiki/Schoolhouse_Blizzard",
          "https://en.wikipedia.org/wiki/Cyclone_Imogen", "https://en.wikipedia.org/wiki/Typhoon_Nesat_(2017)", "https://en.wikipedia.org/wiki/2006_New_England_flood",
          "https://en.wikipedia.org/wiki/Hurricane_Laura", "https://en.wikipedia.org/wiki/Typhoon_Soudelor", "https://en.wikipedia.org/wiki/1991_Perfect_Storm",
          "https://en.wikipedia.org/wiki/Cyclone_Xaver", "https://en.wikipedia.org/wiki/Tropical_Storm_Marco_(2008)", "https://en.wikipedia.org/wiki/Hurricane_Gladys_(1975)",
          "https://en.wikipedia.org/wiki/1944_Great_Atlantic_hurricane", "https://en.wikipedia.org/wiki/Cyclone_Hikaa", "https://en.wikipedia.org/wiki/Typhoon_Utor",
          "https://en.wikipedia.org/wiki/2015_Southeast_Africa_floods", "https://en.wikipedia.org/wiki/Hurricane_Sam", "https://en.wikipedia.org/wiki/Cyclone_Alan",
          "https://en.wikipedia.org/wiki/August_2020_Midwest_derecho", "https://en.wikipedia.org/wiki/1893_San_Roque_hurricane", "https://en.wikipedia.org/wiki/Typhoon_Isa",
          "https://en.wikipedia.org/wiki/Cyclone_Yasa", "https://en.wikipedia.org/wiki/Cyclone_Hola", "https://en.wikipedia.org/wiki/Tropical_Depression_Josie",
          "https://www.artemis.bm/news/cyclone-thomas-doris-insured-loss-finalised-at-eur-248m/",
          "https://www.artemis.bm/news/storm-friederike-industry-loss-put-at-eur-1-465bn-1-8bn-by-perils/|https://www.artemis.bm/news/storm-friederike-industry-loss-nears-e1-7bn-77-of-economic-loss-insured/|https://www.artemis.bm/news/billion-plus-storm-losses-expected-from-dudley-ylenia-eunice-zeynep/",
          "https://www.artemis.bm/news/windstorm-burglind-eleanor-industry-loss-estimate-raised-to-eur-680m/|https://www.artemis.bm/news/storm-burglind-eleanor-industry-loss-estimate-hits-840m/|https://www.artemis.bm/news/storm-burglind-eleanor-industry-loss-estimate-hits-840m/",
          "https://www.artemis.bm/news/extratropical-cyclone-herwart-industry-loss-finalised-at-eur-264m/",
          "https://www.artemis.bm/news/windstorm-mike-niklas-insured-loss-estimated-at-e853m-perils/|https://www.artemis.bm/news/windstorm-mike-niklas-final-loss-estimate-is-reduced-e816m-perils/|https://www.artemis.bm/news/european-windstorm-niklas-losses-in-the-billions-aon-benfield/",
          "https://www.artemis.bm/news/perils-in-e328m-loss-estimate-for-european-windstorms-elon-felix/",
          "https://www.artemis.bm/news/european-windstorm-nadia-malik-industry-loss-estimated-at-eur-272m/",
          "https://www.artemis.bm/news/insured-losses-from-2013-german-catastrophes-near-9-6-billion/",
          "https://www.artemis.bm/news/european-windstorm-series-industry-loss-hiked-10-to-e3-61bn-perils/| https://www.artemis.bm/news/european-windstorm-series-loss-close-to-e3-3bn-perils/|https://www.artemis.bm/news/billion-plus-storm-losses-expected-from-dudley-ylenia-eunice-zeynep/|https://www.artemis.bm/news/billion-plus-storm-losses-expected-from-dudley-ylenia-eunice-zeynep/|https://www.artemis.bm/news/european-windstorm-insured-losses-head-towards-eur-3bn/",
          "https://www.artemis.bm/news/cyclone-gabrielle-industry-loss-estimated-nz-1-543bn-by-perils/", "https://www.artemis.bm/news/us-tornado-storm-outbreak-estimated-a-3bn-insured-loss-by-kcc/",
          "https://www.artemis.bm/news/cyclone-seroja-loss-estimate-lowered-9-to-a394m-by-perils/|https://www.artemis.bm/news/australias-cyclone-seroja-leaves-a434m-insurance-industry-loss/",
          "https://www.artemis.bm/news/industry-loss-from-october-storms-in-australia-estimated-over-a1bn/", "https://en.wikipedia.org/wiki/Drought_in_Australia",
          "https://en.wikipedia.org/wiki/2006-2008_Southeastern_United_States_drought", "https://en.wikipedia.org/wiki/Cyclone_Steve", "https://en.wikipedia.org/wiki/Cyclone_Vayu",
          "https://www.artemis.bm/news/hurricane-eta-us-industry-loss-estimated-around-550m-by-aon/"],
    "dev": ["https://en.wikipedia.org/wiki/Hurricane_Julia_(2010)", "https://en.wikipedia.org/wiki/Hurricane_Ophelia_(2005)", "https://en.wikipedia.org/wiki/Hurricane_Agnes",
         "https://en.wikipedia.org/wiki/Typhoon_Olive_(1971)", "https://en.wikipedia.org/wiki/1933_Texas_tropical_storm",
         "https://www.artemis.bm/news/european-windstorm-could-threaten-catastrophe-bonds/|https://www.artemis.bm/news/storm-friederike-industry-loss-nears-e1-7bn-77-of-economic-loss-insured/",
         "https://en.wikipedia.org/wiki/Hurricane_Brenda_(1973)", "https://www.artemis.bm/news/euro-windstorm-hendrik-ignatz-aurore-industry-loss-estimated-e311m/",
         "https://en.wikipedia.org/wiki/Typhoon_Mawar_(2005)", "https://en.wikipedia.org/wiki/Hurricane_Iris", "https://en.wikipedia.org/wiki/Cyclone_Luban",
         "https://en.wikipedia.org/wiki/Typhoon_Sepat",
         "https://www.artemis.bm/news/insured-losses-from-2013-german-catastrophes-near-9-6-billion/|https://www.artemis.bm/news/2013-global-catastrophe-insured-losses-well-below-average-guy-carpenter/",
         "https://en.wikipedia.org/wiki/Tropical_Storm_Dujuan_(2021)", "https://en.wikipedia.org/wiki/2020_East_Africa_floods",
         "https://www.artemis.bm/news/storm-eberhard-industry-loss-estimated-up-to-eur-1-5bn-by-air/|https://www.artemis.bm/news/perils-pegs-combined-loss-of-storms-draghi-eberhard-at-eur-740m/",
         "https://en.wikipedia.org/wiki/Boulder_Fire", "https://en.wikipedia.org/wiki/Tropical_Storm_Delfina", "https://en.wikipedia.org/wiki/Hurricane_Polo_(2014)",
         "https://en.wikipedia.org/wiki/2021_European_floods",
         "https://www.artemis.bm/news/windstorm-victoria-dennis-industry-loss-said-eur-286m-by-perils/|https://www.artemis.bm/news/euro-windstorm-victoria-dennis-industry-loss-raised-20-to-eur-344m/|https://www.artemis.bm/news/euro-windstorm-victoria-dennis-industry-loss-finalised-at-eur-350m/",
         "https://en.wikipedia.org/wiki/Hurricane_Ignacio_(2003)", "https://en.wikipedia.org/wiki/Manzanita_Fire", "https://en.wikipedia.org/wiki/Hurricane_Earl_(2022)",
         "https://en.wikipedia.org/wiki/Mangum_Fire", "https://en.wikipedia.org/wiki/Typhoon_Xangsane_(2000)", "https://en.wikipedia.org/wiki/Hurricane_Linda_(2015)",
         "https://en.wikipedia.org/wiki/Hurricane_Erick_(2013)",
         "https://www.artemis.bm/news/euro-windstorms-uk-floods-add-up-to-meaningful-insurance-losses/|https://www.artemis.bm/news/perils-increases-european-windstorm-tini-loss-estimate-to-e281m/|https://www.artemis.bm/news/perils-puts-final-european-windstorm-tini-loss-estimate-at-e286m/|https://www.artemis.bm/news/perils-ups-european-windstorm-tini-loss-estimate-to-e253m/",
         "https://en.wikipedia.org/wiki/2022_European_heat_waves", "https://en.wikipedia.org/wiki/Bond_Fire",
         "https://www.artemis.bm/news/over-10-billion-economic-loss-from-global-catastrophes-in-october-aon-benfield/", "https://en.wikipedia.org/wiki/Hurricane_Danielle_(2022)",
         "https://en.wikipedia.org/wiki/Cyclone_Magda", "https://en.wikipedia.org/wiki/2010%E2%80%932011_China_drought", "https://en.wikipedia.org/wiki/Drought_in_Australia",
         "https://en.wikipedia.org/wiki/2017_West_Bengal_floods", "https://en.wikipedia.org/wiki/2003_Canberra_bushfires", "https://en.wikipedia.org/wiki/Tropical_Storm_Jerry_(2001)",
         "https://en.wikipedia.org/wiki/Tropical_Storm_Helene_(2000)", "https://en.wikipedia.org/wiki/2021_Islamabad_flooding", "https://en.wikipedia.org/wiki/2019_Pune_flood",
         "https://www.artemis.bm/news/windstorm-christian-insured-losses-1-7bn-to-2-9bn-estimates-credit-suisse/|https://www.artemis.bm/news/perils-puts-initial-loss-estimate-for-windstorm-christian-at-e994m/|https://www.artemis.bm/news/perils-ups-windstorm-christian-loss-estimate-to-e1-091b/|https://www.artemis.bm/news/losses-mount-in-worst-european-winter-storm-season-since-1990/|https://www.artemis.bm/news/2013-global-catastrophe-insured-losses-well-below-average-guy-carpenter/|https://www.artemis.bm/news/windstorm-christian-insured-losses-1-7bn-to-2-9bn-estimates-credit-suisse/|https://www.artemis.bm/news/insured-losses-from-2013-german-catastrophes-near-9-6-billion/",
         "https://en.wikipedia.org/wiki/McNally_Fire", "https://en.wikipedia.org/wiki/Typhoon_Phanfone_(2014)",
         "https://www.artemis.bm/news/perils-e275m-first-loss-estimate-for-european-windstorm-dirk/|https://www.artemis.bm/news/losses-mount-in-worst-european-winter-storm-season-since-1990/|https://www.artemis.bm/news/perils-investigates-dirk-third-major-european-windstorm-of-season/|https://www.artemis.bm/news/perils-increases-loss-estimate-for-european-windstorm-dirk-to-e370m/|https://www.artemis.bm/news/perils-windstorm-tini-initial-loss-estimate-e245m-dirk-upped-to-e352m/|https://www.artemis.bm/news/perils-investigates-dirk-third-major-european-windstorm-of-season/|https://www.artemis.bm/news/perils-investigates-dirk-third-major-european-windstorm-of-season/|https://www.artemis.bm/news/perils-investigates-dirk-third-major-european-windstorm-of-season/",
         "https://en.wikipedia.org/wiki/2014_Southeast_Europe_floods", "https://en.wikipedia.org/wiki/Hurricane_Fred_(2015)", "https://en.wikipedia.org/wiki/Hurricane_Floyd",
         "https://en.wikipedia.org/wiki/Palmer_Fire",
         "https://www.artemis.bm/news/euro-windstorms-uk-floods-add-up-to-meaningful-insurance-losses/|https://www.artemis.bm/news/losses-mount-in-worst-european-winter-storm-season-since-1990/|https://www.artemis.bm/news/euro-windstorms-uk-floods-add-up-to-meaningful-insurance-losses/|https://www.artemis.bm/news/euro-windstorms-uk-floods-add-up-to-meaningful-insurance-losses/",
         "https://en.wikipedia.org/wiki/Cyclone_Herwart", "https://en.wikipedia.org/wiki/Cyclone_Asani", "https://www.artemis.bm/news/european-severe-storms-tornado-may-aggregate-to-eur-1bn-loss/",
         "https://en.wikipedia.org/wiki/Hurricane_Elsa", "https://en.wikipedia.org/wiki/Tropical_Storm_Cristobal_(2008)", "https://en.wikipedia.org/wiki/1775_Newfoundland_hurricane",
         "https://en.wikipedia.org/wiki/January_2008_North_American_storm_complex", "https://www.artemis.bm/news/losses-mount-in-worst-european-winter-storm-season-since-1990/",
         "https://en.wikipedia.org/wiki/Typhoon_Phanfone", "https://en.wikipedia.org/wiki/2008_Queensland_storms", "https://en.wikipedia.org/wiki/Long_Hollow_Fire",
         "https://en.wikipedia.org/wiki/Cyclone_Ernest", "https://en.wikipedia.org/wiki/Hurricane_Cristobal", "https://en.wikipedia.org/wiki/Tropical_Storm_Kompasu_(2021)",
         "https://en.wikipedia.org/wiki/Tropical_Storm_Talas_(2017)", "https://www.artemis.bm/news/windstorm-ciara-sabine-industry-loss-raised-4-to-eur-1-611bn/",
         "https://en.wikipedia.org/wiki/Typhoon_Alex_(1987)", "https://en.wikipedia.org/wiki/Tropical_Depression_Eight_(1981)", "https://en.wikipedia.org/wiki/Electra_Fire_(2022)",
         "https://en.wikipedia.org/wiki/Cerro_Grande_Fire", "https://en.wikipedia.org/wiki/Cyclone_Hollanda", "https://en.wikipedia.org/wiki/Typhoon_Dot_(1985)",
         "https://en.wikipedia.org/wiki/North_American_blizzard_of_1966", "https://en.wikipedia.org/wiki/Tornado_outbreak_of_April_21%E2%80%9323,_2020",
         "https://en.wikipedia.org/wiki/Typhoon_Agnes_(1984)", "https://en.wikipedia.org/wiki/2021_Western_North_America_heat_wave", "https://en.wikipedia.org/wiki/Typhoon_Kujira_(2009)",
         "https://en.wikipedia.org/wiki/Kincade_Fire", "https://en.wikipedia.org/wiki/Drought_in_Australia", "https://en.wikipedia.org/wiki/Tropical_Storm_Matthew_(2010)",
         "https://en.wikipedia.org/wiki/2008_Chinese_winter_storms", "https://en.wikipedia.org/wiki/Tropical_Storm_Ampil", "https://en.wikipedia.org/wiki/Substation_Fire",
         "https://en.wikipedia.org/wiki/Hurricane_How",
         "https://www.artemis.bm/news/perils-e680m-initial-loss-estimate-for-european-windstorm-xaver/ |https://www.artemis.bm/news/air-european-windstorm-xaver-insured-loss-e700m-to-e1-4-billion/|https://www.artemis.bm/news/perils-increases-european-windstorm-xaver-loss-estimate-to-e759m/|https://www.artemis.bm/news/losses-mount-in-worst-european-winter-storm-season-since-1990/|https://www.artemis.bm/news/2013-global-catastrophe-insured-losses-well-below-average-guy-carpenter/|https://www.artemis.bm/news/insured-losses-from-2013-german-catastrophes-near-9-6-billion/|https://en.wikipedia.org/wiki/Cyclone_Xaver",
         "https://en.wikipedia.org/wiki/Tropical_Storm_Fran_(1984)", "https://en.wikipedia.org/wiki/Tropical_Storm_Usagi_(2018)",
         "https://www.artemis.bm/news/significant-tornado-outbreak-damages-multiple-us-states/|https://www.artemis.bm/news/significant-tornado-outbreak-damages-multiple-us-states/",
         "https://en.wikipedia.org/wiki/Cyclone_Pam",
         "https://www.artemis.bm/news/storm-eberhard-industry-loss-estimated-up-to-eur-1-5bn-by-air/|https://www.artemis.bm/news/perils-pegs-combined-loss-of-storms-draghi-eberhard-at-eur-740m/|https://www.artemis.bm/news/industry-loss-from-eu-storms-dragi-eberhard-raised-to-eur-798m-by-perils/|https://www.artemis.bm/news/eu-windstorms-dragi-eberhard-final-loss-estimate-raised-to-eur-782m-perils/",
         "https://en.wikipedia.org/wiki/Tropical_Storm_Erika", "https://en.wikipedia.org/wiki/Cyclone_Monica", "https://en.wikipedia.org/wiki/2014_Bulgarian_floods",
         "https://en.wikipedia.org/wiki/2022_Dallas_floods",
         "https://en.wikipedia.org/wiki/Tornado_outbreak_of_November_27%E2%80%9328,_2005#:~:text=On%20November%2027%20and%2028,November%206%2C%2012%20and%2015.",
         "https://en.wikipedia.org/wiki/Tropical_Storm_Haiyan_(2007)", "https://en.wikipedia.org/wiki/Hurricane_Carrie", "https://en.wikipedia.org/wiki/2008_South_China_floods",
         "https://en.wikipedia.org/wiki/Dome_Fire_(2020)"]}
