name: Run Unit Tests via Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 1
      - name: Set up Python 3.11
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.11
      - id: cache-dependencies
        name: Cache dependencies
        uses: actions/cache@v2.1.7
        with:
          path: ${{ github.workspace }}/.venv
          key: dependencies-${{ hashFiles('**/poetry.lock') }}
          restore-keys: dependencies-
      - name: Install dependencies
        if: steps.cache-dependencies.cache-hit != 'true'
        run: |
          python3 -m pip install -U pip poetry
          poetry --version
          poetry check --no-interaction
          poetry config virtualenvs.in-project true
          poetry install --no-interaction
      - id: cache-lfs
        name: Cache LFS files
        uses: actions/cache@v2.1.7
        with:
          path: ${{ github.workspace }}/.lfs
          key: lfs-${{ hashFiles('Database/data/*.csv') }}
          restore-keys: lfs-
      - name: Pull LFS files for testing
        if: steps.cache-lfs.cache-hit != 'true'
        run: git lfs pull --include "Database/data/*.csv"
        env:
          GIT_TRACE: 1
      - name: Run tests
        run: poetry run pytest -ra -s tests
