name: Run Unit Tests via Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Pull LFS files for testing
        run: git lfs pull --include "Database/data/*.csv"
        env:
          GIT_TRACE: 1
      - name: Run tests
        run: poetry run pytest -ra -s tests -vv
