name: Run Unit Tests via Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
        env:
          GIT_LFS_SKIP_SMUDGE: 1
      - name: Set up Python 3.11
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.11
          cache: poetry
      - name: Install dependencies
        run: |
          python3 -m pip install -U pip poetry
          poetry --version
          poetry check --no-interaction
          poetry config virtualenvs.in-project true
          poetry install --no-interaction
      - name: Pull LFS (GADM) files for unit tests
        run: git lfs pull --include "Database/data/gadm_world.csv"
        timeout-minutes: 60
        env:
          GIT_TRACE: 1
      - name: Pull LFS (UNSD) files for unit tests
        run: git lfs pull --include "Database/data/UNSD — Methodology.csv"
        timeout-minutes: 60
        env:
          GIT_TRACE: 1
      - name: Run tests
        run: poetry run pytest -ra -s tests
